### ISSUE TITLE
biomes' and naturalbiomes' trees miss leaf decay

### ISSUE THREAD

**Issue by fgaz** [EmptyStar/asuna#64] opened 2023-04-30 12:51 UTC
Leaves of trees from the `biomes` and `naturalbiomes` mods don't decay, unlike leaves of other trees.
Not sure if this is a bug, a missing feature, or just intended behavior.

**Comment by EmptyStar** [comment] 2023-04-30 20:56
It's probably some combination of oversight and leaf decay not included by design. I think some of the trees in the biomes in question were not made with leaf decay in mind and would begin losing leaves as soon as they loaded in. And I'm sure leaf decay would cause leafy ground cover to vanish in dorwinion and nightshade biomes, possibly others too.

I'd be wary of adding leaf decay without extensive testing/repairing of natural tree schematics to ensure they don't decay, and leaves that are used for ground cover would need some kind of solution to remain intact (possibly just a param2 value).

So I won't say that adding leaf decay is unwelcome, but it would be a significant effort that I can't personally prioritize right now.

**Comment by EmptyStar** [comment] 2024-07-28 15:20
I've added leafdecay to the Biomes modpack trees. Natural Biomes does have some support for leaf decay, but some trees don't have enough trunk or have `param2=1` on some leaves which prevents proper leaf decay. I think this is probably best fixed upstream. The reason I fixed it for the Biomes modpack is because I've effectively adopted it as I believe it is no longer maintained by its original author.

I'm going to close this issue for Asuna. For any leaf decay issues in Natural Biomes, please report those issues [upstream](https://github.com/Skandarella/naturalbiomes) and I'll be happy to pull in the fixes (and/or contribute them myself if and when I get the time and will to do so).

**Closed by EmptyStar** 2024-07-28 15:20 UTC
